# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
#This is the standard provider configuration.
# Add providers as need to get them setup in each module.

terraform {
  required_version = ">= 1.1"
  required_providers {
    azurecaf = {
      source  = "aztfmod/azurecaf"
      version = "1.2.23"
    }
    random = {
      source  = "hashicorp/random"
      version = ">=3.4"
    }
  }
}
