# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
#This is the standard provider configuration.
# Add providers as need to get them setup in each module.

terraform {
  required_version = ">= 1.0.8"
}
